### ISSUE TITLE
Manifest inheritance/extension

### ISSUE THREAD

**Issue by Ash258** [Ash258/Scoop-Core#57]
```yml bucket/base.json
version: ahoj
bin: ahoj
persist: "cosi"
```

```yml bucket/base-portable.json
extend: base //TODO: Syntax. It should be only basename of manifest, which will be simple resolved to 
persist: [ "ahoj", "cosi" ]
bin: [ "ahoj, "cosi" ]
```

Version will be conditionally required. 

It will simply load the base manifest. And merge it with the new properties. Forcing the new properties

This will be best for additional version of manifest, including version mutations (winrar, firefox), portability

TODO: Resolve remote installation

https://stackoverflow.com/questions/38717933/jsonschema-attribute-conditionally-required
